//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeNight.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CodeE3Entities : DbContext
    {
        public CodeE3Entities()
            : base("name=CodeE3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<deneme_Result> deneme(Nullable<int> ıd)
        {
            var ıdParameter = ıd.HasValue ?
                new ObjectParameter("ıd", ıd) :
                new ObjectParameter("ıd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<deneme_Result>("deneme", ıdParameter);
        }
    }
}
